/* KeySuite V4.23.14 — BFI Assembly now routes directly to a complete 2-pump System with automatic panel, manifold and tank. */
(()=>{'use strict';
if(window.__KEYSUITE_BFI_V42302__)return;window.__KEYSUITE_BFI_V42302__=true;
const $=id=>document.getElementById(id),DB=()=>window.KeySuiteBFIProductData||{models:[]},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,d=2)=>Number(v||0).toLocaleString('en-MY',{minimumFractionDigits:d,maximumFractionDigits:d});
let data=null,access=null,selectedSeries='ALL',priceMaterial='SS304',brandContext={name:'B.G.Reich',brandSeries:'BFI',sellingSeries:'BFI'};
function rows(){return (data?.bfiProducts?.length?data.bfiProducts:DB().models||[]).slice()}
function brandName(){return brandContext.name||'B.G.Reich'}
function baseModelName(model){return String(model||'').trim().replace(/^BFIN\b/i,'BFI').replace(/[TE]+$/i,'').trim()}
function materialCode(value){return /316|\bBFIN\b/i.test(String(value||''))?'SS316':'SS304'}
function materialLabel(value){return materialCode(value)==='SS316'?'Stainless Steel 316':'Stainless Steel 304'}
function materialModel(model,material='SS304'){const raw=String(model||'').trim().replace(/^BFIN\b/i,'BFI');return materialCode(material)==='SS316'?raw.replace(/^BFI\b/i,'BFIN'):raw}
function motorEffForPhase(phase){return String(phase||'3Ph')==='1Ph'?'IE1':'IE2'}
function motorEffForProduct(product,phase){return Number(product?.motor_hp||0)>0&&Number(product.motor_hp)<=0.75+1e-9?'IE1':motorEffForPhase(phase)}
function displayModel(model,phase='',material='SS304'){const phased=String(phase||'')==='3Ph'?baseModelName(model)+'T':baseModelName(model),selling=String(brandContext.sellingSeries||brandContext.brandSeries||'BFI').trim(),master=materialModel(phased,material);return selling&&selling.toUpperCase()!=='BFI'?master.replace(/^BFIN?\b/i,selling):master}
function displaySeries(value){const selling=String(brandContext.sellingSeries||brandContext.brandSeries||'BFI').trim()||'BFI';return String(value||'').replace(/^BFIN?\b/i,selling)}
function syncProductIdentity(){const selling=String(brandContext.sellingSeries||brandContext.brandSeries||'BFI').trim()||'BFI',brand=brandName();const h1=document.querySelector('#productBfi h1'),help=document.querySelector('#productBfi .page-title-row .muted'),seriesHeading=document.querySelector('#productBfi .product-layout > .card:first-child h2'),modelHeading=document.querySelector('#productBfi .product-layout > .card:last-child h2');if(h1)h1.textContent=`Product · ${selling}`;if(help)help.textContent=`${brand} ${selling} horizontal multistage pump range. Select model, phase, seal and elastomer; open curve or route to Assembly / Quote.`;if(seriesHeading)seriesHeading.textContent=`${selling} Series`;if(modelHeading)modelHeading.textContent=`${selling} Models`;const search=$('bfiProductSearch');if(search)search.placeholder=`Example: ${selling} 8-3-1`}
function phaseFor(product,requested='3Ph'){const phases=product?.phases||['1Ph','3Ph'];return phases.includes(requested)?requested:(phases.includes('3Ph')?'3Ph':phases[0])}
function formatMotorHp(value){const n=Number(value);return Number.isFinite(n)?n.toFixed(2).replace(/0+$/,'').replace(/\.$/,''):''}
function bfiSealDescription(seal='Car/Cer',elastomer='Viton'){const raw=String(seal||'Car/Cer').trim(),norm=raw.toLowerCase().replace(/[\/_-]+/g,' ').replace(/\s+/g,' ').trim(),e=String(elastomer||'Viton').trim()||'Viton';if(!norm||norm==='car cer'||norm==='car sic'||norm==='ca sic'||norm.includes('carbon'))return 'Mechanical Seal';if(norm==='sic sic'||norm.includes('silicon carbide'))return `Mechanical Seal-SiC SiC ${e}`;if(norm==='tc tc'||norm==='tuc tic'||norm.includes('tungsten'))return `Mechanical Seal-TC TC ${e}`;return `Mechanical Seal-${raw.replace(/[\/]+/g,' ').replace(/\s+/g,' ').trim()} ${e}`}
function quoteDescription(product,phase,options={}){const seal=options.seal||'Car/Cer',elastomer=options.elastomer||'Viton',material=materialCode(options.material),modelLabel=options.modelLabel||displayModel(product.model,phase,material),voltage=String(phase||'3Ph')==='1Ph'?240:415,hp=formatMotorHp(product.motor_hp),motorEfficiency=String(options.motorEfficiency||motorEffForPhase(phase)).toUpperCase();return [`${brandName()} Horizontal Multistage Pump Model: ${modelLabel}`,`c/w\t${hp||'-'}HP 2Pole ${motorEfficiency} Motor (${voltage}V / ${phase} / 50Hz)`,`Suction & Discharge: ${product.inlet} x ${product.outlet}`,`Material: ${materialLabel(material)} / ${bfiSealDescription(seal,elastomer)}`].join('\n')}
function currentOptions(){return {material:materialCode($('bfiProductMaterial')?.value),phase:$('bfiProductPhase')?.value||'3Ph',seal:$('bfiProductSeal')?.value||'Car/Cer',elastomer:$('bfiProductElastomer')?.value||'Viton'}}
function find(model){const wanted=baseModelName(model).toLowerCase();return rows().find(r=>String(r.model).toLowerCase()===wanted||String(r.id)===String(model||''))||null}
function pricing(model,phase,mode='quotation',options={}){return window.KeySuitePricing?.findBfiPrice?.(model,phase,{...options,pricingMode:mode})||null}
function bfiSeriesNumber(product){return Number((String(product?.series||product?.model||'').match(/BFI\s+(\d+)/i)||[])[1]||0)}
function bfiThreadDn(value){const text=String(value||'').trim().toUpperCase().replace(/\s+/g,'');const map={'G1':25,'G1¼':32,'G1.25':32,'G1-1/4':32,'G1½':40,'G1.5':40,'G1-1/2':40,'G2':50};return Number(map[text]||0)}
function bfiShutoffHead(product){const family=String(bfiSeriesNumber(product)||''),curve=DB().curves?.[family];if(!curve)return null;const full0=Number(curve.head_per_stage?.[0]),small0=Number(curve.head_per_stage_2?.[0]??full0),mini0=Number(curve.head_per_stage_3?.[0]??small0);if(!Number.isFinite(full0))return null;const full=Math.max(0,Number(product?.fullImpellers??product?.stages??0)||0),small=Math.max(0,Number(product?.smallImpellers||0)||0),mini=Math.max(0,Number(product?.smallestImpellers||0)||0),head=full*full0+small*small0+mini*mini0;return Number.isFinite(head)&&head>0?head:null}
function routeSelection(payload,route='quotation'){
  const product=find(payload?.model||payload?.base_model);if(!product){alert('BFI model could not be found.');return false}
  const phase=phaseFor(product,payload?.motor_phase||payload?.phase||'3Ph'),material=materialCode(payload?.keysuite_material||currentOptions().material),seal=payload?.keysuite_seal||'Car/Cer',elastomer=payload?.keysuite_elastomer||'Viton',enhanced=phase==='3Ph'&&(/E$/i.test(String(payload?.model||payload?.display_model||payload?.quotation_model||''))||payload?.enhanced===true||payload?.enhanced_curve===true);
  if(!window.KeySuiteApp?.ensureQuotationPricingContext?.(`add a BFI pump to the ${route==='assembly'?'Assembly':'quotation'}`))return false;
  const requiredMotorEfficiency=motorEffForProduct(product,phase),selectedMotorEfficiency=requiredMotorEfficiency==='IE1'?'IE1':String(payload?.motor_efficiency_class||payload?.motorEfficiencyClass||payload?.motor_efficiency||requiredMotorEfficiency).toUpperCase(),priceIdentity=phase==='3Ph'?`${baseModelName(product.model)}${enhanced?'E':'T'}`:baseModelName(product.model),quoteModel=materialModel(enhanced?`${baseModelName(product.model)}E`:displayModel(product.model,phase),material),found=pricing(priceIdentity,phase,route==='assembly'?'assembly':'quotation',{motor_hp:Number(product.motor_hp||0),pole:2,motor_efficiency_class:selectedMotorEfficiency,material});
  if(!found){const reason=window.KeySuitePricing?.bfiPriceProblem?.(priceIdentity,phase,{pricingMode:route==='assembly'?'assembly':'quotation',material})||`${material==='SS316'?'BFIN':'BFI'} pricing is unavailable for ${quoteModel}.`;alert(reason);return false}
  if(route!=='assembly'&&!window.KeySuitePricing?.ensureQuoteableCalculation?.(found.calc,quoteModel))return false;
  const suctionDn=bfiThreadDn(product.inlet),dischargeDn=bfiThreadDn(product.outlet),source=window.KeySuitePricing.sourceSnapshot(found),pumpData={...payload,model:product.model,base_model:product.model,quotation_model:quoteModel,display_model:quoteModel,series:product.series,stages:Number(product.stages||0),connection:product.connection,suction:product.inlet,discharge:product.outlet,suction_dn:suctionDn?`DN${suctionDn}`:'',discharge_dn:dischargeDn?`DN${dischargeDn}`:'',motor_kw:Number(product.motor_kw||0),motor_hp:Number(product.motor_hp||0),default_motor_efficiency_class:requiredMotorEfficiency,motor_efficiency_class:selectedMotorEfficiency,motor_phase:phase,motor_voltage:phase==='1Ph'?240:415,frequency_hz:50,shutoff_head_m:bfiShutoffHead(product),keysuite_product_family:'BFI',keysuite_brand_name:brandName(),keysuite_material:material,material_variant:material==='SS316'?'BFIN':'BFI',enhanced};
  const item={model:quoteModel,description:quoteDescription(product,phase,{material,seal,elastomer,modelLabel:quoteModel,motorEfficiency:selectedMotorEfficiency}),qty:1,unitPrice:found.calc.finalPrice,pricingSource:{...source,motor_phase:phase,pump_material:material,seal_faces:seal,seal_elastomer:elastomer},productFamily:'BFI',pumpData,assemblyLevel:route==='assembly'?'COMPLETE_PUMPSET':'PUMPSET_COMPONENT',assemblySection:route==='assembly'?'pumpset':'pump'};
  if(route==='assembly'){const add=window.KeySuiteAssembly?.addItem;if(typeof add!=='function'){alert('Assembly is not available. Please reload KeySuite and try again.');return false}const result=add(item,{type:'system',section:'pumpset'});if(result&&typeof result.catch==='function')result.catch(error=>{console.error('BFI System assembly route failed.',error);alert(error?.message||'Unable to prepare the BFI System assembly.')});return result!==false}
  const row=window.KeySuiteApp?.addExternalQuoteItem?.(item);if(row)window.KeySuiteApp?.showPage?.('quotation');return !!row;
}
function openCurve(model){const product=find(model);if(!product)return false;const runtime=window.KeySuiteV394411ProductCurve||window.KeySuiteV394410ProductCurve||window.KeySuiteV39449ProductCurve||window.KeySuiteV39448ProductCurve;try{if(runtime&&typeof runtime.open==='function'&&runtime.open('BFI',product.model,'BFI')!==false)return true}catch(error){console.warn('Shared BFI Product curve route failed.',error)}return false}
function renderProduct(){const seriesHost=$('bfiProductSeriesList'),grid=$('bfiProductModelGrid'),count=$('bfiProductModelCount');if(!seriesHost||!grid)return;syncProductIdentity();const all=rows(),series=[...new Set(all.map(r=>r.series))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));seriesHost.innerHTML='';['ALL',...series].forEach(s=>{const b=document.createElement('button');b.type='button';b.className='product-series-button'+(selectedSeries===s?' active':'');b.textContent=s==='ALL'?`All ${displaySeries('BFI')}`:displaySeries(s);b.onclick=()=>{selectedSeries=s;renderProduct()};seriesHost.appendChild(b)});const search=String($('bfiProductSearch')?.value||'').trim().toLowerCase(),phase=$('bfiProductPhase')?.value||'3Ph',material=currentOptions().material;const filtered=all.filter(r=>{const ph=phaseFor(r,phase);return (selectedSeries==='ALL'||r.series===selectedSeries)&&(!search||String(r.model).toLowerCase().includes(search)||displayModel(r.model,ph,material).toLowerCase().includes(search))});if(count)count.textContent=`${filtered.length} model${filtered.length===1?'':'s'}`;grid.innerHTML='';filtered.forEach(p=>{const ph=phaseFor(p,phase),row=document.createElement('div');row.className='product-model-row';row.innerHTML=`<h3>${esc(displayModel(p.model,ph,material))}</h3><div class="product-model-actions"><button class="btn secondary product-action-button" type="button" data-bfi-curve data-bfi-model="${esc(p.model)}">Curve</button><button class="btn action-assembly product-action-button" type="button" data-bfi-assembly>Assembly</button><button class="btn action-quote product-action-button" type="button" data-bfi-quote>Quote</button></div>`;row.querySelector('[data-bfi-curve]').onclick=()=>openCurve(p.model);const payload=()=>({model:p.model,motor_phase:ph,keysuite_material:material,keysuite_seal:$('bfiProductSeal')?.value,keysuite_elastomer:$('bfiProductElastomer')?.value});row.querySelector('[data-bfi-assembly]').onclick=()=>routeSelection(payload(),'assembly');row.querySelector('[data-bfi-quote]').onclick=()=>routeSelection(payload(),'quotation');grid.appendChild(row)})}
function priceBooks(p,material='BFI'){return material==='BFIN'?{prices:p.bfinPricesByCurrency||(p.bfinPricesByCurrency={USD:{'1Ph':0,'3Ph':0},RMB:{'1Ph':0,'3Ph':0},MYR:{'1Ph':0,'3Ph':0}}),rarities:p.bfinRarityByCurrency||(p.bfinRarityByCurrency={USD:{'1Ph':'common','3Ph':'common'},RMB:{'1Ph':'common','3Ph':'common'},MYR:{'1Ph':'common','3Ph':'common'}})}:{prices:p.pricesByCurrency,rarities:p.rarityByCurrency}}
function priceCell(p,currency,phase,material='BFI'){const v=priceBooks(p,material).prices?.[currency]?.[phase];return Number.isFinite(Number(v))?Number(v):0}
function rarityCell(p,currency,phase,material='BFI'){return String(priceBooks(p,material).rarities?.[currency]?.[phase]||'common').toLowerCase()}
function renderMaterialPriceList(material='BFI'){const isBfin=material==='BFIN',body=$('bfiPriceRows');if(!body)return;const currency=$('bfiPriceCurrency')?.value||'MYR',search=String($('bfiPriceSearch')?.value||'').trim().toLowerCase(),modelName=p=>isBfin?String(p.model||'').replace(/^BFI\b/i,'BFIN'):String(p.model||''),list=rows().filter(p=>!search||modelName(p).toLowerCase().includes(search)||String(p.model).toLowerCase().includes(search));if($('bfiPriceListHeading'))$('bfiPriceListHeading').textContent=isBfin?'BFIN Models · Stainless Steel 316':'BFI Models · Stainless Steel 304';if($('bfiPriceListCount'))$('bfiPriceListCount').textContent=`${list.length} models · ${currency}`;if($('bfiPriceSearch'))$('bfiPriceSearch').placeholder=isBfin?'Example: BFIN 12-5':'Example: BFI 12-5';body.innerHTML='';for(const p of list){const name=modelName(p),tr=document.createElement('tr');const phaseHtml=ph=>(p.phases||[]).includes(ph)?`<div class="bfi-price-pair"><div class="currency-price-input"><span>${esc(currency)}</span><input type="number" min="0" step="0.01" data-bfi-price="${ph}" value="${priceCell(p,currency,ph,material)}" aria-label="${esc(name)} ${ph} ${esc(currency)} price"></div><select data-bfi-rarity="${ph}"><option value="many">Many</option><option value="common">Common</option><option value="rare">Rare</option><option value="fixed">Fixed</option></select></div>`:'<span class="muted">N/A</span>';tr.innerHTML=`<td><b>${esc(name)}</b></td><td>${phaseHtml('1Ph')}</td><td>${phaseHtml('3Ph')}</td><td><button class="btn" data-bfi-save>Save</button></td>`;for(const ph of ['1Ph','3Ph']){const sel=tr.querySelector(`[data-bfi-rarity="${ph}"]`);if(sel)sel.value=rarityCell(p,currency,ph,material)}tr.querySelector('[data-bfi-save]').onclick=()=>savePriceRow(p,tr,currency,material);body.appendChild(tr)}}
function renderPriceList(){const material=priceMaterial==='SS316'?'BFIN':'BFI';if($('bfiPriceMaterial'))$('bfiPriceMaterial').value=priceMaterial;renderMaterialPriceList(material);window.dispatchEvent(new Event('keysuite-price-list-rendered'))}
async function savePriceRow(p,tr,currency,material='BFI'){const client=window.KeySuiteAuth?.getClient?.();if(!client)return;const get=(attr,ph)=>tr.querySelector(`[${attr}="${ph}"]`),v1=get('data-bfi-price','1Ph'),v3=get('data-bfi-price','3Ph'),r1=get('data-bfi-rarity','1Ph'),r3=get('data-bfi-rarity','3Ph'),button=tr.querySelector('[data-bfi-save]'),isBfin=material==='BFIN';button.disabled=true;button.textContent='Saving…';try{const {error}=await client.rpc(isBfin?'keysuite_save_bfin_product_price_v42705':'keysuite_save_bfi_product_price_v42302',{p_product_id:p.id,p_currency:currency,p_price_1ph:v1?Number(v1.value||0):null,p_price_3ph:v3?Number(v3.value||0):null,p_rarity_1ph:r1?.value||'common',p_rarity_3ph:r3?.value||'common'});if(error)throw error;const books=priceBooks(p,material);for(const [ph,input,sel] of [['1Ph',v1,r1],['3Ph',v3,r3]])if(input){books.prices[currency][ph]=Number(input.value||0);books.rarities[currency][ph]=sel.value}button.textContent='Saved';setTimeout(()=>button.textContent='Save',900);window.KeySuitePricing?.syncPriceListSettings?.({bfiProducts:rows()})}catch(e){console.error(e);alert(`${material} price could not be saved: ${e.message||e}`);button.textContent='Save'}finally{button.disabled=false}}
async function saveRate(currency){const id=currency==='USD'?'bfiUsdMultiplier':'bfiRmbMultiplier',input=$(id),client=window.KeySuiteAuth?.getClient?.(),value=Number(input?.value);if(!client||!(value>0))return;const {error}=await client.rpc('keysuite_save_bfi_multiplier_v42302',{p_currency:currency,p_multiplier:value});if(error){alert(`BFI multiplier could not be saved: ${error.message||error}`);return}data.productMultipliers.BFI={...(data.productMultipliers.BFI||{}),[currency]:value,MYR:1};window.KeySuitePricing?.syncPriceListSettings?.({productMultipliers:data.productMultipliers});}
function init(next,userAccess){data=next||data||{};access=userAccess||access;const currency=$('bfiPriceCurrency'),savedCurrency=String(localStorage.getItem('ks_bfi_price_currency')||currency?.value||'MYR').toUpperCase(),savedMaterial=String(localStorage.getItem('ks_bfi_price_material')||'SS304').toUpperCase();if(currency&&['MYR','USD','RMB'].includes(savedCurrency))currency.value=savedCurrency;priceMaterial=savedMaterial==='SS316'?'SS316':'SS304';if(data?.productMultipliers?.BFI){if($('bfiUsdMultiplier'))$('bfiUsdMultiplier').value=Number(data.productMultipliers.BFI.USD||1).toFixed(4);if($('bfiRmbMultiplier'))$('bfiRmbMultiplier').value=Number(data.productMultipliers.BFI.RMB||1).toFixed(4)}renderProduct();renderPriceList()}
function bind(){if(document.body.dataset.bfi42302Bound)return;document.body.dataset.bfi42302Bound='1';$('bfiProductSearch')?.addEventListener('input',renderProduct);$('bfiProductPhase')?.addEventListener('change',renderProduct);$('bfiPriceSearch')?.addEventListener('input',renderPriceList);$('bfiPriceMaterial')?.addEventListener('change',event=>{priceMaterial=String(event.target.value||'SS304').toUpperCase()==='SS316'?'SS316':'SS304';localStorage.setItem('ks_bfi_price_material',priceMaterial);renderPriceList()});$('bfiPriceCurrency')?.addEventListener('change',event=>{localStorage.setItem('ks_bfi_price_currency',String(event.target.value||'MYR').toUpperCase());renderPriceList()});window.addEventListener('KEYSUITE_V393_BRAND_CONTEXT_CHANGED',ev=>{if(String(ev.detail?.family||'').toUpperCase()!=='BFI')return;brandContext={...brandContext,...ev.detail};renderProduct()});window.addEventListener('message',ev=>{const m=ev.data||{};if(m.type==='KEYSUITE_PRODUCT_FRAME_READY'&&String(m.family||'').toUpperCase()==='BFI'){$('productBfiSelectorFrame')?.contentWindow?.postMessage({type:'KEYSUITE_V393_BRAND_CONTEXT',brand:brandContext},'*')}})}
document.addEventListener('change',event=>{if(event.target?.id==='bfiProductMaterial')renderProduct()});
function pageShown(id){if(id==='productBfi')renderProduct();if(id==='bfiPriceList')renderPriceList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()},{once:true});else{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()}
window.KeySuiteBFI={version:'4.23.14',init,rows,find,renderProduct,renderPriceList,pageShown,openCurve,routeSelection,quoteDescription};
})();
